import Collapsible from "./common/Collapsible";

export default function FAQ() {
  return (
    <section id="faq" className="text-center flex flex-col gap-6 items-center justify-center max-w-4xl mx-auto mt-16 px-8 py-12 bg-black/50 rounded-3xl border-4 border-white/20" title="Frequently Asked Questions">
      {/* Name and tag */}
      <h1 className="!text-5xl md:text-6xl font-black">
        🤔 FAQ TIME! 🤔
      </h1>
      <div className="flex items-center justify-center gap-6 mt-6">
        <div className="h-2 bg-gradient-to-r from-transparent via-white/50 to-transparent w-32 rounded-full"></div>
        <span className="text-3xl">❓</span>
        <div className="h-2 bg-gradient-to-r from-transparent via-white/50 to-transparent w-32 rounded-full"></div>
      </div>

      <div className="flex flex-col gap-4 mt-10 w-full">
        <Collapsible title="What is the Magic 8 Ball?">
          <p className="!mb-2 text-lg font-bold">
            The Magic 8 Ball is a classic fortune-telling toy that answers <strong>yes or no</strong> questions.
          </p>
          <p className="text-lg font-bold"><strong>For example: "Will I win the lottery?" → "Very doubtful." 🎱</strong></p>
          <br />
          <p className="text-lg font-bold">
            Want the full history? Read the {" "}
            <a
              href="https://en.wikipedia.org/wiki/Magic_8_Ball"
              target="_blank"
              rel="noopener noreferrer"
            >
              Wikipedia article
            </a> if you're a <em>NERDDDDDDDDDDDDD</em>. 🤓
          </p>
        </Collapsible>

        <Collapsible title="What is this site?">
          <p className="text-lg font-bold">
            A <strong>Magic 8 Ball</strong> remake—except the answers are generated by AI personalities instead of canned phrases. Basically it's a glorified AI wrapper. 🤖✨
          </p>
        </Collapsible>

        <Collapsible title="The AI gave me terrible advice. Can I sue you?">
          <p className="text-lg font-bold">
            Get an actual therapist for life advice instead. 🛋️💭
          </p>
        </Collapsible>

        <Collapsible title="Why did you make this?">
          <p className="text-lg font-bold">
            What the heck am I supposed to do? Touch grass? 🌱😱
          </p>
        </Collapsible>

        <Collapsible title="I hate you.">
          <p className="text-lg font-bold">
            I hate you, too. 💜😘
          </p>
        </Collapsible>
      </div>
    </section>
  );
}