import Collapsible from "./common/Collapsible";

export default function FAQ() {
  return (
    <section id="faq" className="text-center flex flex-col gap-2 items-center justify-center max-w-3xl mx-auto mt-12 px-6" title="Frequently Asked Questions">
      {/* Name and tag */}
      <h1 className="!text-4xl md:text-5xl font-bold text-white">
        Frequently Asked Questions
      </h1>
      <div className="flex items-center justify-center gap-4 mt-4">
        <hr className="h-px border-white/30 w-36" />
        <span className="w-2 h-2  rounded-full bg-white/30"></span>
        <hr className="h-px border-white/30 w-36" />
      </div>

      <div className="flex flex-col gap-1 mt-8 w-full">
        <Collapsible title="What is the Magic 8 Ball?">
          <p className="!mb-1">
            The Magic 8 Ball is a classic fortune-telling toy that answers <strong>yes or no</strong> questions.
          </p>
          <p><strong>For example: “Will I win the lottery?” → “Very doubtful.”</strong></p>
          <br />
          <p>
            Want the full history? Read the {" "}
            <a
              href="https://en.wikipedia.org/wiki/Magic_8_Ball"
              target="_blank"
              rel="noopener noreferrer"
            >
              Wikipedia article
            </a> if you're a <em>NERDDDDDDDDDDDDD</em>.
          </p>
        </Collapsible>

        <Collapsible title="What is this site?">
          <p>
            A <strong>Magic 8 Ball</strong> remake—except the answers are generated by AI personalities instead of canned phrases. Basically it's a glorified AI wrapper.
          </p>
        </Collapsible>

        <Collapsible title="The AI gave me terrible advice. Can I sue you?">
          <p>
            Get an actual therapist for life advice instead.
          </p>
        </Collapsible>

        <Collapsible title="Why did you make this?">
          <p>
            What the heck am I supposed to do? Touch grass?
          </p>
        </Collapsible>

        <Collapsible title="I hate you.">
          <p>
            I hate you, too.
          </p>
        </Collapsible>
      </div>
    </section>
  );
}