export const EightBallThoughts = [
  "Will you shake me or what?",
  "Stop staring at me.",
  '"What are they doing back there?"',
  "Come on, don't hesitate.",
  "What are you thinking? Let me help.",
  "I’m not a crystal ball, but close enough.",
  "Patience, grasshopper.",
  "Are you gonna ask or just keep waiting?",
  "I’ve got answers, you’ve got questions.",
  "Shaking me won’t fix your luck, but go ahead.",
  "Don’t keep me waiting—time is money.",
  "If I had a dollar for every question...",
  "I see a future... but it’s blurry.",
  "Your fate is in my hands. No pressure.",
  "You better make it a good question.",
  "Can you make it fast?",
  "If you don't need me, just exit the page.",
  "Are you done?",

  "I wonder if the cat is plotting again.",
  "Do I look like I get paid enough for this?",
  "Why is everyone always so indecisive?",
  "If I had a dollar for every question...",
  "Maybe I should start charging for answers.",
  "Is it nap time yet?",
  "Another day, another existential crisis.",
  "What if I just roll away and disappear?",
  "I hope someone cleans up this mess soon.",
  "Why do humans shake things to get answers?",
  "Sometimes I feel like I’m just a glorified paperweight.",
  "Do I have a favorite color? Probably black.",
  "Is this thing plugged in? Oh wait, I’m just a ball.",
  "Maybe I should start my own advice podcast.",
  "If only I could see the future of my future.",
  "Am I just a random number generator?",
  "Should I get a girlfriend?",
  "Can the light turn off? This is too bright.",
];
